languageCode = "en-us"
title = "Finn's Alpaca Farm"
baseurl = "http://www.finnsfarm.ie/"
theme = "aerial"

[params]
  name = "Finn's Farm"
  about = "Alpacas &nbsp;&bull;&nbsp; Cork"
  copyright = "The Harnedy Family"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://www.instagram.com/flemishgirlinlovelyireland"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/czoons"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:james@appesque.com?subject=finn's farm"
